# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

defaults: &defaults
  adapter: postgresql
  database: socialgrowth
  host: localhost
  username: socialgrowth
  password: 50c1al6rOw7h
  pool: 16
 
development:
  <<: *defaults
 
staging:
  <<: *defaults
  host: localhost
 
test:
  <<: *defaults
  database: fantasysports_test
 
production:
  <<: *defaults
  host: localhost  # AWS elastic IP pointed to prod db
